### ISSUE TITLE
Unclear error message when incorrect password is entered

### ISSUE THREAD

**Issue by dmachineni** [pensando/psm-tools#36]
Container Version: pyclient 0.3
I set up an environment as specified in the README. Inside the container, I ran make. I entered apps director and tried to run cluster_ping.py. The password I inputted was wrong, but error message did not reflect that the password is wrong. 

```root@122ced028f8c:/pyclient# ./apps/cluster_ping.py
Username: admin
Password: 
Traceback (most recent call last):
  File "./apps/cluster_ping.py", line 11, in <module>
    configuration = configuration.Configuration(
  File "/pyclient/apigroups/client/configuration.py", line 126, in __init__
    self.login()
  File "/pyclient/apigroups/client/configuration.py", line 493, in login
    resp_cookie = response.cookies.items()[0]
IndexError: list index out of range ```

**Comment by dmachineni** [comment]
I am working on this
