### ISSUE TITLE
Permission problem on pyclient container

### ISSUE THREAD

**Issue by jsilberm** [pensando/psm-tools#49]
```
root@c3c1dbbbb8a2:/pyclient# make
make getswagger
make[1]: Entering directory '/pyclient'
python3 getswagger.py
Traceback (most recent call last):
  File "getswagger.py", line 68, in <module>
    downloadSwaggerFiles()
  File "getswagger.py", line 18, in downloadSwaggerFiles
    os.mkdir("swagger")
PermissionError: [Errno 13] Permission denied: 'swagger'
make[1]: *** [Makefile:16: getswagger] Error 1
make[1]: Leaving directory '/pyclient'
make: *** [Makefile:6: default] Error 2
root@c3c1dbbbb8a2:/pyclient# ls -ltra
total 52
-rw-rw-r--  1 1535700619 1535700619   62 Jul 29 18:31 .gitignore
-rw-rw-r--  1 1535700619 1535700619  624 Jul 29 18:31 Dockerfile
-rw-rw-r--  1 1535700619 1535700619  780 Jul 29 18:31 Makefile
-rw-rw-r--  1 1535700619 1535700619 1370 Jul 29 18:31 README.md
drwxrwxr-x  2 1535700619 1535700619 4096 Jul 29 18:31 apps
drwxrwxr-x  2 1535700619 1535700619 4096 Jul 29 18:31 docs
-rwxrwxr-x  1 1535700619 1535700619   72 Jul 29 18:31 entrypoint.sh
-rw-rw-r--  1 1535700619 1535700619  282 Jul 29 18:31 gen.sh
-rw-rw-r--  1 1535700619 1535700619  114 Jul 29 18:31 genconfig.json
-rw-rw-r--  1 1535700619 1535700619 2875 Jul 29 18:31 getswagger.py
drwxrwxr-x 11 1535700619 1535700619 4096 Jul 29 18:31 openapi-generator
-rw-rw-r--  1 1535700619 1535700619 1131 Jul 29 18:31 requirements.txt
drwxrwxr-x  6 1535700619 1535700619 4096 Jul 29 18:31 .
drwxrwxr-x  2 1535700619 1535700619 4096 Jul 29 18:31 utils
drwxr-sr-x  1 root       root         18 Jul 29 18:43 ..
```

Main branch

**Additional context**

**Comment by jsilberm** [comment]
Can no longer reproduce
